Copied all files from a project
ilias-zet/online-store pull request #1
Opened 2023-07-31 16:54 UTC by WhiskasWannaCry

2023-08-01 10:32 UTC, ilias-zet commented on backend/data.json
@WhiskasWannaCry Do you use this data.json file? Remove it if you don't.

2023-08-01 12:07 UTC, ilias-zet commented on backend/routes/auth.routes.js
don't use dot as separator in file name. Use camelCase instead

2023-08-01 12:12 UTC, ilias-zet commented on backend/routes/auth.routes.js
> +        res.status(500).json({ message: "Что-то пошло не так, попробуйте снова" })
Use english as default language for UI and server responses. We can create a localization later, but now it's not necessary

2023-08-01 12:15 UTC, ilias-zet commented on backend/routes/oneProduct.js
Rename file to 'products.js'. Move all requests, related with products (such as all products, single product, e.t.c) to this file

2023-08-01 12:22 UTC, ilias-zet commented on backend/routes/oneProduct.js
> +        res.status(500).json({ message: "Что-то пошло не так, попробуйте снова" })
Translate to english

2023-08-01 12:24 UTC, ilias-zet commented on backend/routes/oneProduct.js
> +router.get('/one-product', (request, response) => {
Do you actually use this request? Delete it if you don't

2023-08-01 17:54 UTC, ilias-zet commented on backend/index.js
> +const MONGO_URL = process.env.MONGO_URL
PORT constant is referring to .env.PORT variable, but there is no PORT var in .env file. Add it

2023-08-01 17:57 UTC, ilias-zet commented on backend/index.js
> +})
res.json is not asynchronous function, you don't need to use await keyword before function execution

2023-08-01 18:13 UTC, ilias-zet commented on backend/index.js
> +})
should new user be in response in case if registration successfully? If yes, fix your code above

2023-08-01 18:31 UTC, ilias-zet commented on backend/models.js
> +module.exports = User;
You can't export variables in this way. Update it using following example
https://stackoverflow.com/questions/16631064/declare-multiple-module-exports-in-node-js

2023-08-01 18:33 UTC, ilias-zet commented on backend/routes/products.js
> +
delete this

2023-08-01 18:37 UTC, ilias-zet commented on backend/routes/products.js
> +  await response.json(products)
You try to find objects with property "main_category" equals to category variable value. But Product schema doesn't contain property "main_category". Are you sure your schemas is correct? Update schemas with correct field names from database

2023-08-02 18:47 UTC, ilias-zet commented on backend/index.js
> +const PORT = process.env.PORT;
Add this variable to .env and .env.example

2023-08-02 18:48 UTC, ilias-zet commented on backend/index.js
> +async function start() {
Don't commit debug logs. Never

2023-08-02 18:49 UTC, ilias-zet commented on backend/index.js
> +  throw new Error(".env Error: Some variable is not defined or does not exist")
Add same check for PORT

2023-08-02 18:50 UTC, ilias-zet commented on backend/index.js
> +  }
Delete this

2023-08-02 18:51 UTC, ilias-zet commented on backend/index.js
> +})
Response should send registered user to client

2023-08-02 18:51 UTC, ilias-zet commented on backend/index.js
> +  console.log(categories)
delete debug logs

2023-08-02 19:12 UTC, ilias-zet commented on backend/models.js
> +const User = mongoose.model('User', userSchema, 'users')
rename this variables to Products and Users

2023-08-02 19:40 UTC, ilias-zet commented on backend/routes/products.js
> +router.get('/getProductsByCategory',async (request, response) => {
Rename this to 'getProducts'

2023-08-02 22:04 UTC, WhiskasWannaCry commented on backend/index.js
> +  const { userData } = request.query
Now I uses POST req

2023-08-04 14:37 UTC, ilias-zet commented on backend/.env.example
> +SECRET_KEY_JWT="YOUR_KEY_FOR_JWT"
This .env property is not used in any file. You have same property in config.js. It's better to store all properties in one file, so remove one of them

2023-08-04 14:41 UTC, ilias-zet commented on backend/package.json
You have not installed 'jsonwebtoken' and 'express-validator' libs in your package.json (you can see it if you delete node_modules folder and run 'npm install' command)

2023-08-04 14:44 UTC, ilias-zet commented on backend/authController.js
> +const bcrypt = require("bcryptjs");
Unused variable images, remove it

2023-08-04 14:50 UTC, ilias-zet commented on backend/authController.js
> +      const user = new Users({ userName, userSurname,userEmail, userPassword:hashPassword,roles:[userRole.value] });
I think it's wrong to store roles in database. You'll have maximum 10 roles so it can be stored in JS array.

2023-08-04 14:55 UTC, ilias-zet commented on backend/authController.js
> +        return res.status(400).json({messageValidPassword:"Password is not valid"})
You should have same error structure for all errors. (for example { message: 'err msg'}). Don't call error properties like this

2023-08-04 14:56 UTC, ilias-zet commented on backend/authController.js
> +      return res.json({user})
Unused variable 'token'

2023-08-04 14:58 UTC, ilias-zet commented on backend/authController.js
> +}
Is it debugging-request? If yes, remove it

2023-08-04 14:58 UTC, ilias-zet commented on backend/config.example
move this property to .env

2023-08-04 14:59 UTC, ilias-zet commented on backend/index.js
> +const authRouter = require("./routes/auth")
Unused variable 'Users'

2023-08-04 15:03 UTC, ilias-zet commented on backend/models.js
> +  },
Don't specify _id in your schemas. By the way, it have type is Schema.ObjectId, not Number

2023-08-04 15:05 UTC, ilias-zet commented on backend/models.js
> +  },
you can describe this fields in short way, like `{ field: String }`

2023-08-04 15:08 UTC, ilias-zet commented on backend/models.js
> +  images: String,
If you have string array, just write `[String]` as a type, no matter how many strings inside this array

2023-08-04 15:11 UTC, ilias-zet commented on backend/models.js
> +
Store roles in JS array in separate file (if you sure you actually need to store roles)

2023-08-04 15:17 UTC, ilias-zet commented on backend/models.js
> +});
If you have some object, Person, for example. Don't call it's fields like personName, personAge, e.t.c. If you call it like this you would get result like person.personName, person.personAge. It's ugly. Call properties just like name, surname, email, e.t.c

2023-08-05 05:38 UTC, WhiskasWannaCry commented on backend/.env.example
> +SECRET_KEY_JWT="YOUR_KEY_FOR_JWT"
I tried to use .env, but this not working

2023-08-05 08:33 UTC, ilias-zet commented on frontend/public/logo192.png
Delete this

2023-08-05 08:33 UTC, ilias-zet commented on frontend/public/logo512.png
Delete this

2023-08-05 08:35 UTC, ilias-zet commented on frontend/public/manifest.json
> +    }
Delete this lines which refers to removed images

2023-08-05 08:37 UTC, ilias-zet commented on frontend/public/robots.txt
Delete this file

2023-08-05 08:37 UTC, ilias-zet commented on frontend/src/App.css
> +    min-height: 100%;
Fix indents here

2023-08-05 08:39 UTC, ilias-zet commented on frontend/src/App.css
> +/* фон нашего модального окна */
Remove comments

2023-08-05 08:44 UTC, ilias-zet commented on frontend/src/App.js
> +  let [searchParams, setSearchParams] = useSearchParams();
Rename this state to just 'user' instead of 'loginedUser'

2023-08-05 08:47 UTC, ilias-zet commented on frontend/src/App.js
> +        <Header
I think it's better to App.js return single element, not fragment (</>) with other elements inside.

2023-08-05 08:51 UTC, ilias-zet commented on frontend/src/App.js
> +  const { isOpenedLogin, openLogin, closeLogin } = useLogin(false);
You can save value returned from these hooks to single variable and then pass & destructure it inside other components

2023-08-05 09:11 UTC, ilias-zet commented on frontend/src/App.js
> +          element={
Usually, main page located in route '/', so we'll do same. Rename this route

2023-08-05 09:12 UTC, ilias-zet commented on frontend/src/App.js
> +            ></Body>
Rename this component to HomePage

2023-08-05 09:13 UTC, ilias-zet commented on frontend/src/App.js
> +            />
Rename this component to ProductsPage

2023-08-05 09:13 UTC, ilias-zet commented on frontend/src/App.js
> +          </PageWithCategories>}
Rename this component to CategoriesPage

2023-08-05 09:14 UTC, ilias-zet commented on frontend/src/App.js
> +      </Routes>
Rename this component to ProductPage

2023-08-05 09:15 UTC, ilias-zet commented on frontend/src/App.js
> +          element={
Rename route to just 'categories'

2023-08-05 09:22 UTC, ilias-zet commented on frontend/src/App.js
> +      ></Login>
Create separate component called Auth or Аuthorization or smth like this. It should include both of them: signIn and signUp. Best practice for this is just create form and state 'isSignIn', for example. If isSignIn, fill form with content of signIn component, else - signUp component

2023-08-05 09:24 UTC, ilias-zet commented on frontend/src/Footer/Footer.css
Move this style to Footer.js component using styled-components and delete this CSS file.

2023-08-05 09:26 UTC, ilias-zet commented on frontend/src/Footer/Footer.css
> +    bottom: 0;
- remove comment
- bottom property is useless here, remove it

2023-08-05 09:27 UTC, ilias-zet commented on frontend/src/Footer/Footer.js
> +
Delete unused imports

2023-08-05 09:28 UTC, ilias-zet commented on frontend/src/Footer/Footer.js
> +
Use styled-componenst syntax

2023-08-05 09:29 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +  margin-left: 20px;
Don't commit comments like this

2023-08-05 09:30 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +`;
Delete this

2023-08-05 09:31 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +`;
Delete this comment

2023-08-05 09:32 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +`;
Fix indents here

2023-08-05 09:34 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +  isOpened,
Rename to Header

2023-08-05 09:34 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +  setLoginedUser,
Remove unused variables

2023-08-05 09:36 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +  };
Remember that after you change routes values you should change navigation properties too

2023-08-05 09:42 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +  }
In this case you use it in the following instance of code
`<SignUpLogInBtnContainer onClick={() => clickHandlerForSignUp()}>`
where `clickHandlerForSignUp` function just call another one `open` function. So you can just call `open` function instead of `clickHandlerForSignUp`
`<SignUpLogInBtnContainer onClick={() => open()}>`
By the way, if handler pass same params as you need inside callback function, you can use following syntax
`onClick={open}`

2023-08-05 09:46 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +    <HeaderContainer>
Same situation as in object called 'Person' with 'personAge' params.
If you declare container inside Header component, don't use prefix 'header' before element name. Use Container instead of HeaderContainer

2023-08-05 09:47 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +      <LogoContainer onClick={() => clickHandler()}>
use `onClick={clickHandler}` syntax here

2023-08-05 09:49 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +            <A href="/all-categories">Categories</A>
Don't forget you need to update routes.
I also thing that using `<a href="">` is not that good idea. Maybe better replace it with something else and add click handler

2023-08-05 09:59 UTC, ilias-zet commented on frontend/src/Header/Header.js
> +                {loginedUser.userName + " " + loginedUser.userSurname}
destructure this properties in the top of component

2023-08-05 10:05 UTC, ilias-zet commented on frontend/src/Header/Header1.js
Delete this component

2023-08-05 10:05 UTC, ilias-zet commented on frontend/src/Header/HeaderSearch.js
Delete this component

2023-08-08 14:31 UTC, WhiskasWannaCry commented on backend/authController.js
> +      return res.json({user})
Now i use this variable

2023-08-08 14:38 UTC, WhiskasWannaCry commented on backend/models.js
> +
I don't need to store roles

2023-08-08 17:42 UTC, ilias-zet requested changes

2023-08-08 17:42 UTC, ilias-zet commented on frontend/public/index.html
> +    -->
Remove this

2023-08-08 17:42 UTC, ilias-zet commented on frontend/public/index.html
> +    -->
Remove this

2023-08-10 15:35 UTC, ilias-zet requested changes

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +      setCategories(imgsAndNameCategoriesArr);
Why request that return categories called 'getImages'? Change it

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +      {/* <LoadingCard></LoadingCard> */}
don't commit comments

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +`;
Why width 90%?

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +  min-height: 100%;
Why width 95%? Delete it if need

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +                categoryNameStrForHandler={elem.main_category}
these two properties have same values, so you can remove one of them. Also rename it to just 'name'

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +                categoryImage={elem.image}
rename this prop to 'image'

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +            return (
destructure this 'elem' object

2023-08-10 15:35 UTC, ilias-zet commented on frontend/src/Pages/CategoriesPage/CategoriesPage.js
> +                setSearchParams={setSearchParams}
just pass 'onClick' handler as a param for 'Category' component and describe callback inside 'CategoriesPage' component

2023-08-11 19:58 UTC, WhiskasWannaCry commented on frontend/src/Header/Header.js
> +  grid-template-rows: 100% 100%;
I need display grid for more adaptive

2023-08-14 20:44 UTC, WhiskasWannaCry commented on frontend/src/App.js
> +        setIsopenedMenu={setIsopenedMenu}
Now I use this state for scroll handler on App.js

2023-08-15 17:49 UTC, ilias-zet requested changes

2023-08-17 10:28 UTC, ilias-zet commented on frontend/src/App.js
> +            ></CategoriesPage>
don't pass searchParams as a component parameters. Call `useSearchParams` in Categories component instead

2023-08-17 21:39 UTC, ilias-zet requested changes

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +              responsedProduct.length +
maybe "found" is better here

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/setupTests.js
Delete this file

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +
Remove empty lines

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +  const userRepeatPassword = useInput("");
- Set "" as default 'initialValue' property value for useInput hook and remove empty strings here.
[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters](url)
- remove 'user' prefix here
- lets change useInput hook to make it return not object but array, and then we can call returned values with any name

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +      ) {
just disable signup button if some of these variables is empty

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +        };
in single line

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +          "http://localhost:8000/auth/registration",
destructure data

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +          {
userData should be in payload only, not in query

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +          alert("Успешная регистрация!");
translate to english

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +            : "Unexpected registration error";
there should be `e?.response.data?.message OR "Unexpected registration error"`

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +          email,
There is no variable called userData in this scope

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +          "http://localhost:8000/auth/login",
Destructure { data }

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +        }
Translate to English

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +              <OtherInput {...userRepeatPassword}></OtherInput>
Bad naming, change it

2023-08-17 21:39 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +    let userData;
rename

2023-08-26 20:23 UTC, ilias-zet requested changes

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/LoadingCard.js
> +        <div className="loader"></div>
don't use classNames. Use styled components instead

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/LoadingCard.js
> +      </div>
render multiple elements using array map method

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/App.css
> +}
remove

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/App.css
> +}
remove

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/App.css
> +}
remove

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/LoadingCard.js
> +import "../App.css";
don't import app.css here

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/LoadingCard.js
> +
too many indents

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +  height: 200px;
stop using `width: 90%`. Use margin/padding instead

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +        {product.images ? <CardImage src={product.images}></CardImage> : null}
destructure product

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +      </CardTitle>
This is pure CSS solution
https://stackoverflow.com/questions/486563/overflowhidden-dots-at-the-end

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +      </CardIsAmazonSeller>
You don't need ternary operator here, bc it returns null only if availability is null

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/Search.js
unused component. Remove it

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/useInput.js
> +  ]
write it in single line

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/useLogin.js
Unused hook. Remove it

2023-08-26 20:23 UTC, ilias-zet commented on frontend/src/shared/useInput.js
Create hooks folder on same nesting level as pages and move all hooks there

2023-08-28 12:17 UTC, WhiskasWannaCry commented on frontend/src/pages/Home.js
> +        )}
I want to show random categories, that's why I get more than I need

2023-08-28 21:05 UTC, ilias-zet commented on frontend/src/pages/Home.js
> +        )}
Anyway, you should do it on server, and send only those categories that you want to show

2023-09-06 19:58 UTC, ilias-zet requested changes

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Categories.js
> +        <Skeleton
You need isLoaded state wherever you have to load data before render

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +
Use import syntax wherever you import modules

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +    });
Same error

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +  const [product, setProduct] = useState(null);
this state is array so it should be called `products` instead of `product` and it's initial state should be an empty array

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +        <SkeletonContainer>
You need isLoaded state here

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +          </ProductsCounter>
Client-side filter is too expensive for performance. We'll redo it to server-side filter later. Just ignore this message.

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/pages/Products.js
> +                <ProductCard product={product} key={product._id}></ProductCard>
Don't use return keyword in arrow function if you use it to return some value. Just put it directly after the arrow

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +      }
Same error

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Authorization.js
> +              Sign Up
Click handlers not working on disabled buttons anyway. No needed to return null if button disabled

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Category.js
> +  cursor: pointer;
Just CategoryName

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Category.js
> +    e.preventDefault();
No needed to pass second `name` param because it comes as props from parent component.

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Category.js
> +      <ImgContainer>
So you can use simple callback syntax here

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/Category.js
> +    e.preventDefault();
Are you sure this function should be named like this?

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +      </CardImageContainer>
Add some empty image in case if there is no images

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/ProductCard.js
> +      <CardIsAmazonSeller>
Product have special `priceCurrency` prop that contains currency name. It can be different than '$' so change it.

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/theme.js
Learn about [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), we'll use it later for theming

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/shared/utils.js
> +}
With structure of function like this you can't catch the error inside your components. This function shouldn't have try/catch blocks, move them to components, where you using this functions

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +              setIsopenedMenu(false)
Move to separate handler

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +            }}
use same handler as in conversation above, but with another parameter

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +          </NavBtn>
You have same styles for all nav icons, create styled-component for all of them

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +            <img alt='' src={cartImg} height={"50%"}></img>
NavBtn is a span, so it shouldn't have 'href' property

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +          )}
same expressions for ternary operator. Are you sure you actually need it here?

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/components/Header.js
> +          <Switcher isOpenedMenu={isOpenedMenu} theme={theme}></Switcher>
Create separate component ThemeSwitch and move all logic associated with theme switcher there.
Also your switch should have fixed width and height to prevent situations like this
<img width="49" alt="image" src="https://github.com/ilias-zet/online-store/assets/76498638/db72e285-40b5-436b-ad91-edc156b0b8b1">

2023-09-06 19:58 UTC, ilias-zet commented on frontend/src/App.js
> +      <ThemeProvider theme={theme === 'light' ? lightTheme : darkTheme}>
You don't need fragment here anymore

2023-11-13 10:22 UTC, merged